[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.buildArgs]
VITE_BACKEND_URL = "${{VITE_BACKEND_URL}}"
VITE_CLERK_PUBLISHABLE_KEY = "${{VITE_CLERK_PUBLISHABLE_KEY}}"

[deploy]
startCommand = "/docker-entrypoint.sh nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
