[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.nsq"

[deploy]
startCommand = "/start-nsq.sh"
healthcheckPath = "/ping"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
